server:
  port: 8080

spring:
  profiles:
    default: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
logging:
  level:
    org:
      apache:
        coyote:
          http11: DEBUG

